
services:

  service-a:
    build: ./service-a
    ports:
      - "8001:8000"
    depends_on:
      - redis

  service-b:
    build: ./service-b
    ports:
      - "8002:8000"
    depends_on:
      - redis
      - service-c

  service-c:
    build: ./service-c
    ports:
      - "8003:8000"
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - service-a
      - service-b