events {}

http {

    upstream ops_services {
        server service-a:8000;
        server service-b:8000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://ops_services;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}